/* Cryptomonopoly — deterministic game engine (pure reducer).
 * The reducer is a pure function of (state, action): no globals, no Date,
 * no Math.random. Dice are generated by the acting device and carried in the
 * action, so every peer applying the same action stream converges on the
 * same state — that is what keeps a real WebXDC multi-device game in sync.
 */
(function (global) {
  "use strict";
  const B = global.CryptoBoard;

  function initialState() {
    return {
      players: {},   // id -> {id,name,token,color,cash,pos,inJail,jailLeft,alive}
      order: [],     // player ids in turn order
      turn: 0,       // index into order
      ownership: {}, // tileIndex -> {ownerId, level}
      pot: B.POT_START,
      log: [],
      over: false,
      winner: null,
      pending: null, // {kind:'buy', pos, player}
      eventDraws: 0, // deterministic counter for the event deck
      lastDice: null,
      canRollAgain: false,
      conseqDoubles: 0,
      phase: "lobby", // "lobby" -> "play"
    };
  }

  const reducer = (state, action) => reduce(state, action);

  function reduce(s0, action) {
    const s = clone(s0);
    const log = (m) => { s.log.push(m); if (s.log.length > 120) s.log.shift(); };

    switch (action.type) {
      case "ADD_PLAYER": {
        const p = action.player;
        if (!p || !p.id || s.players[p.id]) return s0;
        if (s.phase !== "lobby") return s0; // no joins after the game has started
        if (Object.keys(s.players).length >= 6) return s0;
        s.players[p.id] = {
          id: p.id, name: p.name, token: p.token, color: p.color,
          cash: B.START_CASH, pos: 0, inJail: false, jailLeft: 0, alive: true,
        };
        s.order.push(p.id);
        log(`👤 ${p.name} joined the chain.`);
        return s;
      }
      case "START": return actStart(s, action, log);
      case "ROLL": return actRoll(s, action, log);
      case "BUY": return actBuy(s, action, log);
      case "PASS_BUY": return actPassBuy(s, action, log);
      case "UPGRADE": return actUpgrade(s, action, log);
      case "END_TURN": return actEndTurn(s, action, log);
      case "RESET": return initialState();
      default: return s0;
    }
  }

  function actStart(s, action, log) {
    const n = s.order.filter((id) => s.players[id] && s.players[id].alive).length;
    if (s.phase !== "lobby" || n < 2) return s;
    s.phase = "play";
    log("🚀 Game started!");
    return s;
  }

  // ---- ROLL ----------------------------------------------------------
  function actRoll(s, action, log) {
    const p = s.players[action.player];
    if (!p || !p.alive) return s0of(s);
    if (s.order[s.turn] !== action.player) return s0of(s);
    if (s.pending) { log("⚠️ Resolve your pending action first."); return s; }
    if (s.over) return s;

    const [d1, d2] = action.dice || [1, 1];
    const total = d1 + d2;
    const doubles = d1 === d2;
    s.lastDice = [d1, d2];
    s.canRollAgain = false;
    s.phase = "play"; // first roll locks the roster

    // Jail handling (they already serve their first "turn" as an attempt).
    if (p.inJail) {
      if (doubles) {
        p.inJail = false; p.jailLeft = 0;
        log(`🔓 ${p.name} rolled doubles and escaped!`);
        s.conseqDoubles = 0;
      } else if (p.jailLeft > 0) {
        p.jailLeft--;
        log(`⛓ ${p.name} is rugged (${p.jailLeft} left).`);
        if (p.jailLeft <= 0) {
          const bond = 50;
          p.inJail = false; p.cash -= bond; s.pot += bond;
          log(`💸 ${p.name} paid a 50 bond to leave.`);
        } else {
          return s; // stayed in jail, no movement
        }
      }
    }

    // three doubles in a row => jail
    s.conseqDoubles = doubles ? s.conseqDoubles + 1 : 0;
    if (s.conseqDoubles >= 3) {
      toJail(s, p, log);
      log("🎲 Three doubles — straight to jail.");
      return s;
    }

    const start = p.pos;
    let np = start + total;
    let wrapped = false;
    while (np >= B.BOARD_SIZE) { np -= B.BOARD_SIZE; wrapped = true; }
    p.pos = np;
    if (wrapped || np === 0) { p.cash += B.GO_SALARY; log(`💰 ${p.name} passed GO (+${B.GO_SALARY}).`); }

    const tile = B.tileByIndex(np);
    log(`🎲 ${p.name} rolled ${d1}+${d2} → ${tile.sym} ${tile.name}.`);
    land(s, p, np, log);

    // doubles -> may roll again (unless a buy is pending or game over)
    s.canRollAgain = doubles && !s.pending && !s.over;
    return s;
  }

  function s0of(s) { return s; } // keep mutated copy; harmless

  // ---- landing resolution -------------------------------------------
  function land(s, p, pos, log) {
    const tile = B.tileByIndex(pos);
    switch (tile.type) {
      case B.type.GO: break;
      case B.type.PROP:
      case B.type.EXCH: {
        const o = s.ownership[pos];
        if (!o) {
          if (p.cash >= tile.price) {
            s.pending = { kind: "buy", pos, player: p.id };
            log(`🛒 ${p.name} may buy ${tile.name} (${tile.price}).`);
          } else log(`🪙 ${p.name} can't afford ${tile.name} (${tile.price}).`);
        } else if (o.ownerId === p.id) {
          log(`🏠 ${p.name} owns ${tile.name}.`);
        } else {
          const rent = rentFor(s, tile, o, log);
          const owner = s.players[o.ownerId];
          log(`💸 ${p.name} pays ${rent} to ${owner.name} (${tile.name}).`);
          pay(s, p, owner, rent, log);
        }
        break;
      }
      case B.type.TAX: {
        const tax = Math.max(40, Math.floor(p.cash * 0.1));
        p.cash -= tax; s.pot += tax;
        log(`🧾 ${p.name} pays ${tax} network fee into the pot.`);
        break;
      }
      case B.type.AIRDROP: { p.cash += 120; log(`🪂 ${p.name} caught an airdrop +120.`); break; }
      case B.type.POT: {
        const w = s.pot; p.cash += w; s.pot = 0;
        log(`🫙 ${p.name} claims the Free-Mint pot +${w}.`);
        break;
      }
      case B.type.JAIL: log(`⛓ ${p.name} is just visiting.`); break;
      case B.type.RUG: toJail(s, p, log); break;
      case B.type.EVENT: {
        const card = B.EVENT_DECK[s.eventDraws % B.EVENT_DECK.length];
        s.eventDraws++;
        log(`✳️ Event: ${card.text}`);
        applyEvent(s, p, card, log);
        break;
      }
    }
  }

  function rentFor(s, tile, o, log) {
    if (tile.type === B.type.EXCH) {
      const n = countOwned(s, o.ownerId, B.type.EXCH);
      return [25, 50, 100, 200][Math.min(n, 4) - 1] || 0;
    }
    return tile.rent[o.level] || tile.rent[0];
  }

  function countOwned(s, ownerId, type) {
    let n = 0;
    for (const k in s.ownership) {
      const t = B.tileByIndex(+k);
      if (t.type === type && s.ownership[k].ownerId === ownerId) n++;
    }
    return n;
  }

  function applyEvent(s, p, card, log) {
    if (card.kind === "cash") {
      const v = card.value;
      if (card.toPot) { p.cash -= v; s.pot += v; }
      else if (card.fromPot) { const give = Math.min(s.pot, v); p.cash += give; s.pot -= give; }
      else p.cash += v;
      if (p.cash <= 0) bankrupt(s, p, log);
    } else if (card.kind === "jail") {
      toJail(s, p, log);
    } else if (card.kind === "move") {
      if (card.target < p.pos) { p.cash += B.GO_SALARY; log(`💰 Passed GO.`); }
      p.pos = card.target % B.BOARD_SIZE;
    }
  }

  function toJail(s, p, log) {
    p.pos = B.JAIL_INDEX; p.inJail = true; p.jailLeft = 3; s.conseqDoubles = 0;
    log(`🥾 ${p.name} is rugged and sent to jail!`);
  }

  function pay(s, payer, payee, amount, log) {
    const amt = Math.min(payer.cash, amount);
    payer.cash -= amt; payee.cash += amt;
    if (payer.cash <= 0 && amount > 0) bankrupt(s, payer, log);
  }

  function bankrupt(s, p, log) {
    p.alive = false; p.cash = 0;
    for (const k in s.ownership) if (s.ownership[k].ownerId === p.id) delete s.ownership[k];
    log(`🪦 ${p.name} went bankrupt.`);
    maybeEnd(s, log);
  }

  function maybeEnd(s, log) {
    const alive = s.order.filter((id) => s.players[id] && s.players[id].alive);
    if (alive.length <= 1) { s.over = true; s.winner = alive[0] || null; log(`🏆 ${s.winner ? s.players[s.winner].name : "?"} wins!`); }
  }

  // ---- action helpers ------------------------------------------------
  function actBuy(s, action, log) {
    const p = s.players[action.player];
    const pend = s.pending;
    if (!p || !pend || pend.player !== action.player || pend.kind !== "buy") return s;
    const tile = B.tileByIndex(pend.pos);
    if (p.cash >= tile.price) {
      p.cash -= tile.price;
      s.ownership[pend.pos] = { ownerId: p.id, level: 0 };
      s.pending = null;
      log(`🛒 ${p.name} bought ${tile.name} (${tile.price}).`);
    } else { s.pending = null; log(`❌ ${p.name} couldn't afford it.`); }
    return s;
  }
  function actPassBuy(s, action, log) {
    const pend = s.pending;
    if (!pend || pend.player !== action.player || pend.kind !== "buy") return s;
    const tile = B.tileByIndex(pend.pos);
    s.pending = null;
    log(`${s.players[action.player].name} passed on ${tile.name}.`);
    return s;
  }
  function actUpgrade(s, action, log) {
    const p = s.players[action.player];
    const o = s.ownership[action.tile];
    const tile = B.tileByIndex(action.tile);
    if (!p || !p.alive) return s;
    if (s.pending) return s;
    if (!o || o.ownerId !== action.player) return s;
    if (tile.type !== B.type.PROP || o.level >= 4) return s;
    if (p.cash < tile.up) { log(`⚠️ ${p.name} can't afford a node upgrade.`); return s; }
    p.cash -= tile.up; o.level++;
    log(`🏗 ${p.name} staked a node on ${tile.name} (lvl ${o.level}).`);
    return s;
  }
  function actEndTurn(s, action, log) {
    const p = s.players[action.player];
    if (!p || !p.alive) return s;
    if (s.order[s.turn] !== action.player) return s;
    if (s.pending) { log("⚠️ Resolve your pending action first."); return s; }
    s.canRollAgain = false;
    let i = s.turn;
    for (let st = 0; st < s.order.length; st++) {
      i = (i + 1) % s.order.length;
      if (s.players[s.order[i]].alive) break;
    }
    s.turn = i;
    log(`➡️ Turn → ${s.players[s.order[i]].name}.`);
    maybeEnd(s, log);
    return s;
  }

  function clone(o) { return JSON.parse(JSON.stringify(o)); }

  // helpers for the UI (not pure state, just conveniences)
  function currentPlayer(s) { return s.players[s.order[s.turn]] || null; }
  function canAct(s, playerId) { return s.order[s.turn] === playerId && !s.over; }
  function myPending(s, playerId) { return s.pending && s.pending.player === playerId ? s.pending : null; }

  global.CryptoEngine = { initialState, reducer, currentPlayer, canAct, myPending };
})(typeof window !== "undefined" ? window : globalThis);
